<?php

$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/a%20new%20horizon.jpg");
file_put_contents('get-images/a-new-horizon-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/a%20rising%20community.jpg");
file_put_contents('get-images/a-rising-community-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/accidental%20tourist.jpg");
file_put_contents('get-images/accidental-tourist-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/angel%20of%20mercy.jpg");
file_put_contents('get-images/angel-of-mercy-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/beauty%20underneath.jpg");
file_put_contents('get-images/beauty-underneath-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/brass%20maiden.jpg");
file_put_contents('get-images/brass-maiden-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/broadway%20nights.jpg");
file_put_contents('get-images/broadway-nights-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/by%20the%20stars.jpg");
file_put_contents('get-images/by-the-stars-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/candy%20bar.jpg");
file_put_contents('get-images/candy-bar-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/carousel.jpg");
file_put_contents('get-images/carousel-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/catch%20of%20the%20day.jpg");
file_put_contents('get-images/catch-of-the-day-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/celebrating%20the%20arts.jpg");
file_put_contents('get-images/celebrating-the-arts-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/collection%20of%20stars.jpg");
file_put_contents('get-images/collection-of-stars-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/definitely%20downtown.jpg");
file_put_contents('get-images/definitely-downtown-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/dominique.jpg");
file_put_contents('get-images/dominique-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/fairway%20maiden.jpg");
file_put_contents('get-images/fairway-maiden-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/flight.jpg");
file_put_contents('get-images/flight-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/flower%20garden.jpg");
file_put_contents('get-images/flower-garden-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/flying%20spirit.jpg");
file_put_contents('get-images/flying-spirit-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/fresh%20from%20the%20sea.jpg");
file_put_contents('get-images/fresh-from-the-sea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/full%20circle.jpg");
file_put_contents('get-images/full-circle-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/gliding%20through%20the%20bay.jpg");
file_put_contents('get-images/gliding-through-the-bay-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/hats%20off%20to%20th%20navy.jpg");
file_put_contents('get-images/hats-off-to-the-navy-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/heart%20of%20the%20sea.jpg");
file_put_contents('get-images/heart-of-the-sea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/holiday%20sands%20mermaid.jpg");
file_put_contents('get-images/holiday-sands-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/hope.jpg");
file_put_contents('get-images/hope-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/jealous%20mistress.jpg");
file_put_contents('get-images/jealous-mistress-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/jestacular.jpg");
file_put_contents('get-images/jestacular-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/jester%20mermaid.jpg");
file_put_contents('get-images/jester-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/jewel%20of%20the%20sea.jpg");
file_put_contents('get-images/jewel-of-the-sea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/jewel%20the%20barmaid.jpg");
file_put_contents('get-images/jewel-the-barmaid-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/justicalthing.jpg");
file_put_contents('get-images/justicalthing-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/lady%20of%20the%20links.jpg");
file_put_contents('get-images/lady-of-the-links-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/life.%20celebrated%20daily.jpg");
file_put_contents('get-images/life-celebrated-daily-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/lighted%20mermaid.jpg");
file_put_contents('get-images/lighted-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/liquid%20energy.jpg");
file_put_contents('get-images/liquid-energy-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/literacy.jpg");
file_put_contents('get-images/literacy-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/lola.jpg");
file_put_contents('get-images/lola-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/low%20tide.jpg");
file_put_contents('get-images/low-tide-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/maid%20in%20voyage.jpg");
file_put_contents('get-images/maid-in-voyage-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/maid%20of%20lobster.jpg");
file_put_contents('get-images/maid-of-lobster-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/media%20mermaid.jpg");
file_put_contents('get-images/media-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/meimadeline.jpg");
file_put_contents('get-images/meimadeline-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/memory.jpg");
file_put_contents('get-images/memory-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mirror%20mosaic%20ii.jpg");
file_put_contents('get-images/mirror-mosaic-ii-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mirror%20mosaic.jpg");
file_put_contents('get-images/mirror-mosaic-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mishell.jpg");
file_put_contents('get-images/mishell-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/miss%20nato.jpg");
file_put_contents('get-images/miss-nato-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/miss%20virginia%20vine.jpg");
file_put_contents('get-images/miss-virginia-vine-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/moomaid.jpg");
file_put_contents('get-images/moo-maid-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mujeres%20del%20mar.jpg");
file_put_contents('get-images/mujeres-del-mar-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mymphork.jpg");
file_put_contents('get-images/mymphork-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mystique.jpg");
file_put_contents('get-images/mystique-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/mythical%20sirena.jpg");
file_put_contents('get-images/mythical-sirena-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/norfolk,%20a%20banner%20city.jpg");
file_put_contents('get-images/norfolk-a-banner-city-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/norfolk,%20gateway%20to%20the%20sea.jpg");
file_put_contents('get-images/norfolk-gateway-to-the-sea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/ocarina.jpg");
file_put_contents('get-images/ocarina-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/ocean%20patina.jpg");
file_put_contents('get-images/ocean-patina-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/of%20the%20sea.jpg");
file_put_contents('get-images/of-the-sea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/palace%20princess%20beatrice.jpg");
file_put_contents('get-images/palace-princess-beatrice-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/penny.jpg");
file_put_contents('get-images/penny-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/picture%20frame%20mermaid.jpg");
file_put_contents('get-images/picture-frame--mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/plated%20mermaid.jpg");
file_put_contents('get-images/plated-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/princess%20azalea.jpg");
file_put_contents('get-images/princess-azalea-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/rainbow.jpg");
file_put_contents('get-images/rainbow-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/reaching%20for%20a%20dream.jpg");
file_put_contents('get-images/reaching-for-a-dream-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/reflections.jpg");
file_put_contents('get-images/reflections-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/riverview.jpg");
file_put_contents('get-images/riverview-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/rock-ell.jpg");
file_put_contents('get-images/rock-ell-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/scales%20of%20justice.jpg");
file_put_contents('get-images/scales-of-justice-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/sea%20maiden.jpg");
file_put_contents('get-images/sea-maiden-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/sea%20shimmer.jpg");
file_put_contents('get-images/sea-shimmer-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/seasonal%20maid.jpg");
file_put_contents('get-images/seasonal-maid-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/shamrock.jpg");
file_put_contents('get-images/shamrock-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/she%20sells%20seashells%20mermaid.jpg");
file_put_contents('get-images/she-sells-seashells-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/shellina.jpg");
file_put_contents('get-images/shellina-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/ships%20ahoy.jpg");
file_put_contents('get-images/ships-ahoy-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/silver%20mermaid.jpg");
file_put_contents('get-images/silver-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/siren.jpg");
file_put_contents('get-images/siren-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/spectrum%20gold.jpg");
file_put_contents('get-images/spectrum-gold-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/sue-nami.jpg");
file_put_contents('get-images/sue-nami-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/sybil.jpg");
file_put_contents('get-images/sybil-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/techno%20mermaid.jpg");
file_put_contents('get-images/techno-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/the%20jewel%20of%20norfolk.jpg");
file_put_contents('get-images/the-jewel-of-norfolk-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/the%20norfolk%20admiralette.jpg");
file_put_contents('get-images/the-norfolk-admiralette-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/toga.jpg");
file_put_contents('get-images/toga-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/uss%20wisconsin.jpg");
file_put_contents('get-images/uss-wisconsin-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/wavey%20mermaid.jpg");
file_put_contents('get-images/wavey-mermaid-whro-mermaid-2009.jpg', $image);
$image = file_get_contents("http://www.whro.org/cii/gcc/solutions/march142009/gcclevel4/WebDesign/GloucesterHS/assets/mermaids/yuma%20yah.jpg");
file_put_contents('get-images/yuma-yah-mermaid-whro-mermaid-2009.jpg', $image);
?>

